"""Os 90 rituais do desafio, um por dia (dia 1 = 3 de outubro)."""

RITUAIS = [
    # outubro
    "Arrume a cama como se fosse de hotel.",
    "Tome o café da manhã sem o celular por perto.",
    "Compre flores para você, nem que seja uma só.",
    "Monte uma playlist para a sua semana.",
    "Faça uma caminhada de 20 minutos sem fones.",
    "Use uma roupa que você ama num dia comum.",
    "Escreva três coisas pelas quais você é grata.",
    "Acenda uma vela no fim do dia.",
    "Monte um prato bonito, mesmo que seja só para você.",
    "Fotografe cinco detalhes bonitos do seu dia.",
    "Organize a gaveta que mais te incomoda.",
    "Leia dez páginas de um livro.",
    "Tome um banho demorado, sem pressa nenhuma.",
    "Mande uma mensagem carinhosa para alguém.",
    "Pare para assistir ao pôr do sol.",
    "Beba água numa taça bonita.",
    "Faça um piquenique, nem que seja no chão da sala.",
    "Escreva uma carta para você do futuro.",
    "Desligue as telas uma hora antes de dormir.",
    "Conheça um café onde você nunca foi.",
    "Cozinhe uma receita que você nunca fez.",
    "Arrume a mesa para uma refeição comum.",
    "Alongue o corpo logo ao acordar.",
    "Saia para um encontro com você mesma.",
    "Troque a roupa de cama e perfume o travesseiro.",
    "Escute um álbum inteiro, do início ao fim.",
    "Escreva sobre uma memória feliz da infância.",
    "Faça uma limpeza no rolo da câmera.",
    "Cuide de uma planta ou plante algo novo.",
    # novembro
    "Releia as suas intenções e responda o checkpoint.",
    "Coma uma fruta devagar, prestando atenção no sabor.",
    "Use o seu perfume favorito para ficar em casa.",
    "Liste dez coisas que te fazem feliz.",
    "Volte para casa por uma rua diferente.",
    "Prepare um chá e beba sentada, sem fazer mais nada.",
    "Doe algo que você não usa mais.",
    "Escreva um elogio sincero para você mesma.",
    "Assista a um filme que te conforta.",
    "Prepare um café da manhã especial.",
    "Fique quinze minutos em silêncio.",
    "Arrume o seu cantinho de trabalho ou estudo.",
    "Tire uma foto sua de que você goste.",
    "Faça uma pausa ao ar livre no meio do dia.",
    "Passeie por uma livraria ou biblioteca.",
    "Escreva o que você quer sentir em dezembro.",
    "Dance uma música inteira, sozinha.",
    "Prepare uma marmita caprichada.",
    "Hidrate o corpo inteiro, com calma.",
    "Diga não para algo que não te faz bem.",
    "Monte um mural de inspirações.",
    "Almoce longe da mesa de trabalho.",
    "Aprenda algo novo por vinte minutos.",
    "Ligue (não mande áudio) para alguém que você ama.",
    "Escreva sobre algo que você superou este ano.",
    "Esvazie e organize a sua bolsa.",
    "Vá dormir trinta minutos mais cedo.",
    "Faça um passeio sem destino.",
    "Cozinhe uma receita de família.",
    "Escreva cinco coisas que deram certo este mês.",
    # dezembro
    "Revisite o seu mapa e responda o checkpoint.",
    "Decore um cantinho da casa.",
    "Faça um mimo para alguém, sem motivo.",
    "Leia um poema em voz alta.",
    "Faça o seu skincare sem pressa, como um ritual.",
    "Coma um doce que você ama, sem culpa.",
    "Escreva como seria a sua rotina ideal.",
    "Faça uma faxina de quinze minutos com música alta.",
    "Acorde cedo para ver o nascer do sol.",
    "Comece a sua lista de desejos para o ano novo.",
    "Monte um look novo só com peças que você já tem.",
    "Deixe um bilhete para alguém da sua casa.",
    "Respire fundo cinco vezes antes de cada refeição.",
    "Prepare um jantar à luz de velas.",
    "Reveja as suas fotos favoritas do ano.",
    "Caminhe à noite olhando as luzes de fim de ano.",
    "Faça um presente com as suas mãos.",
    "Escreva o que você aprendeu sobre você este ano.",
    "Deixe o celular em outro cômodo por uma hora.",
    "Asse algo que deixe a casa cheirosa.",
    "Escreva três sonhos, sem se censurar.",
    "Tome um café num lugar bonito.",
    "Agradeça a alguém que fez diferença no seu ano.",
    "Prepare algo especial para a noite de hoje.",
    "Descanse sem culpa. Hoje é só isso.",
    "Escute as músicas que marcaram o seu ano.",
    "Conte o seu ano em dez fotos.",
    "Escreva o que você quer deixar no ano que termina.",
    "Escreva o que você quer levar para o ano novo.",
    "Prepare um pequeno ritual para amanhã.",
    "Releia este caderno, responda o checkpoint e celebre você.",
]

assert len(RITUAIS) == 90, len(RITUAIS)
